
= `cargoPublish`

_cargoPublish {two-colons} AttrSet -> Effect_

Deploys package to https://www.crates.io[crates.io], the Rust community's crate repository.

Example:

```nix
effects.cargoPublish {
  secretName = "cargo-api-token";
  src = ./.;
}
```

Example secret:

```json
  "cargo-api-token": {
    "kind": "Secret",
    "data": {
      "token": "..."
    },
    "condition": {
      "and": [
        { "isOwner": "my-github-org" },
        { "isRepo": "my-site-repo" }
      ]
    }
  }
```

[[parameters]]
== `Parameters`

[[param-secretName]]
=== `secretName`

The secret that will be looked up in xref:hercules-ci-agent:ROOT:secrets-json.adoc[`secrets.json`].

The `data` field must contain a `"token"` field, with a string value that is a Cargo API token. To make one, navigate to https://crates.io/settings/tokens[API tokens] and use btn:[New Token].

[[param-extraDeployArgs]]
=== `extraPublishArgs`

Extra arguments to pass to the `cargo publish` invocation.

[[param-src]]
=== `src`

Example: `src = ./.;`

Path to the source code of the package to publish.

`src` is unpacked by the Nixpkgs https://nixos.org/manual/nixpkgs/stable/index.html#variables-controlling-the-unpack-phase[`unpackPhase`].

[[param-manifestPath]]
=== `manifestPath`

String containing the path to a `Cargo.toml`, default: `Cargo.toml`. Relative paths are relative to the unpacked `src`.

A store path subpath could be passed instead, bypassing `unpackPhase`.

[[param-targetDir]]
=== `targetDir`

Directory for all generated artifacts
Default: $(mktemp -d)

[[param-extraBuildInputs]]
=== `extraBuildInput`

Extra build inputs present in the environment where `cargo publish` is executed
