
= `runNixOS`

_runNixOS {two-colons} AttrSet -> Effect_

Deploy a NixOS configuration to a machine over SSH.

Example (Flakes):

```nix
hci-effects.runNixOS {
  name = "deploy";
  configuration = self.nixosConfigurations.zeus;
  ssh.destination = "root@zeus.local";
  system = "aarch64-linux";
  secretsMap.ssh = "deploy-ssh";
  userSetupScript = ''
    writeSSHKey
    cat >>~/.ssh/known_hosts <<EOF
    zeus.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
    EOF
  '';
}
```

TIP: This function has a how-to guide. See xref:guide/deploy-a-nixos-machine.adoc[] for a step by step guide to deploy to an existing NixOS machine.


[[parameters]]
== Parameters


[[param-buildOnDestination]]
=== `buildOnDestination`

Default: value of `ssh.buildOnDestination`, which defaults to `false`.

Overrides xref:reference/nix-functions/ssh.adoc#param-buildOnDestination[`ssh.buildOnDestination`]. Defer builds to the destination host instead of pre-building in CI.


[[param-config]]
=== `config`

You may want to use xref:param-configuration[] instead.

This option allows you to insert a custom NixOS invocation, in case your
configuration has already been invoked with the module system.

When this option is set, xref:param-system[], xref:param-configuration[] and xref:param-nixpkgs[] are ignored.


[[param-configuration]]
=== `configuration`

A NixOS configuration or module.

Example: `configuration = ./configuration.nix;`

Example (Flakes): `configuration = self.nixosConfigurations.foo;`

Required, unless you set xref:param-config, which is not the preferred solution.

When this option is set to a pre-evaluated configuration, as in the latter example, xref:param-system[], xref:param-configuration[] and xref:param-nixpkgs[] are ignored.

[[param-nixpkgs]]
=== `nixpkgs`

Required when `configuration` is a module or file.

Path of the Nixpkgs sources to use. These also include the NixOS sources.

Default: `pkgs.path`, where `pkgs` is the Nixpkgs invocation that included the effects overlay.


[[param-secretsMap]]
=== `secretsMap`

See xref:reference/nix-functions/mkEffect.adoc#param-secretsMap[`secretsMap` in `mkEffect`]

Example:

```nix
    secretsMap.ssh = "myuser-ssh";
```


[[param-ssh]]
=== `ssh`

See the named arguments in xref:reference/nix-functions/ssh.adoc[]. Example:

```nix
  ssh.destination = "root@example.com";
```


[[param-system]]
=== `system`

Optional, legacy.

Preferably, this is set in the configuration itself, in `nixpkgs.hostPlatform`.

`nixos-generate-config` sets that option automatically in `hardware-configuration.nix`.


[[param-userSetupScript]]
=== `userSetupScript`

Example:

```nix
    userSetupScript = ''
      writeSSHKey
      cat >>~/.ssh/known_hosts <<EOF
      203.0.113.2 ecdsa-sha2-nistp256 AA.....pw=
      EOF
    '';
```

See:

* xref:reference/bash-functions/writeSSHKey.adoc[]
* xref:reference/nix-functions/mkEffect.adoc#param-userSetupScript[`userSetupScript` in `mkEffect`]


[[return-value]]
== Return value

An effect that switches the NixOS system as configured.

The effect has the following attributes in addition to the attributes returned
by xref:reference/nix-functions/mkEffect.adoc#return-value[`mkEffect`].

[[attr-config]]
=== `config`

The `config` parameter of the module system. This can be used to inspect the
system configuration before committing it. For example:

```
nix repl --file ci.nix
nix-repl> my-host.prebuilt.config.services.postgresql.enable
false
```

[[attr-prebuilt]]
=== `prebuilt`

A derivation representing the built system configuration.

[[attr-prebuilt.config]]
==== `prebuilt.config`

Same as <<attr-config>>.


[discrete]
== See also

* xref:guide/deploy-a-nixos-machine.adoc[] -- a step by step guide to deploy to an existing NixOS machine

* xref:reference/nix-functions/runNixOps.adoc[`runNixOps`] -- provision interrelated machine configurations and other cloud resources

* xref:reference/nix-functions/runArion.adoc[`runArion`] -- deploy services to Docker using NixOS, Nix or Docker-based images

* xref:reference/nix-functions/runNixDarwin.adoc[`runNixDarwin`] -- the macOS equivalent for deploying to a single Apple machine configured with nix-darwin
